### ISSUE TITLE
Install related issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by k7n2g** [YouPHPTube/YouPHPTube#1818]
Hi have Trouble trying to install YouPHPTube   have tried Vultr Digital ocean and other servers 
 will not install  tried Ubuntu 16.04  now on 18.04   can not get database connection from YouPHPTube  
 get this::  Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)

Yes i have a user and privileges,   followed this install procedure,  How to install LAMP, FFMPEG and Git on a fresh Ubuntu 18.x.
Installed Ubuntu server 18.04,   can connect to mysql with Root and Password no problem 
 added root password  stopped  auth_socket,  changed to mysql_native_password, 
FLUSH PRIVILEGES;
restarted all services.
sudo apt install php-mbstring php-gettext
sudo phpenmod mbstring
sudo systemctl restart apache2

bind-address  =0.0.0.0

Port 3306 open

MYSQL LOG.
2019-06-26T11:36:09.680082Z 0 [Note]   - '127.0.0.1' resolves to '127.0.0.1';
2019-06-26T11:36:09.680125Z 0 [Note] Server socket created on IP: '127.0.0.1'.
2019-06-26T11:36:09.893490Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190626 12:36:09
2019-06-26T11:36:10.067393Z 0 [Note] Event Scheduler: Loaded 0 events
2019-06-26T11:36:10.067820Z 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.7.26-0ubuntu0.18.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  (Ubuntu)
2019-06-26T11:47:08.124496Z 2 [Note] Access denied for user ''@'localhost' (using password: NO)
2019-06-26T12:00:29.751770Z 3 [Note] Access denied for user ''@'localhost' (using password: NO)
2019-06-26T12:08:10.082262Z 4 [Note] Access denied for user ''@'localhost' (using password: NO)
2019-06-26T12:08:59.218830Z 5 [Note] Access denied for user ''@'localhost' (using password: NO)
2019-06-26T12:09:01.852032Z 6 [Note] Access denied for user ''@'localhost' (using password: NO)
2019-06-26T12:09:04.386249Z 7 [Note] Access denied for user ''@'localhost' (using password: NO)

http://81.150.166.169/YouPHPTube/install/index.php

sudo mysql_secure_installation
Tried Single commands all installs no problem.

sudo nano /etc/apache2/apache2.conf

Have now reinstalled everything nine times  still wont work. Obviously i am doing something stupid  can you help please Dave
sudo apt update
sudo apt upgrade

Installed https://github.com/DanielnetoDotCom/YouPHPTube/wiki/How-to-install-LAMP,-FFMPEG-and-Git-on-a-fresh-Ubuntu-18.x-for-YouPHPTube-version-4.x-or-newer

sudo apt install phpmyadmin php-mbstring php-gettext

sudo phpenmod mbstring

sudo systemctl restart apache2

sudo mysql

SELECT user,authentication_string,plugin,host FROM mysql.user;

Output
+------------------+-------------------------------------------+-----------------------+-----------+
| user | authentication_string | plugin | host |
+------------------+-------------------------------------------+-----------------------+-----------+
| root | | auth_socket | localhost |
| mysql.session | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| mysql.sys | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| debian-sys-maint | *8486437DE5F65ADC4A4B001CA591363B64746D4C | mysql_native_password | localhost |
| phpmyadmin | *5FD2B7524254B7F81B32873B1EA6D681503A5CA9 | mysql_native_password | localhost |
+------------------+-------------------------------------------+-----------------------+-----------+
5 rows in set (0.00 sec)

ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'; "where password is you new password"

FLUSH PRIVILEGES;

SELECT user,authentication_string,plugin,host FROM mysql.user;

Output
+------------------+-------------------------------------------+-----------------------+-----------+
| user | authentication_string | plugin | host |
+------------------+-------------------------------------------+-----------------------+-----------+
| root | *DE06E242B88EFB1FE4B5083587C260BACB2A6158 | mysql_native_password | localhost |
| mysql.session | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| mysql.sys | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost |
| debian-sys-maint | *8486437DE5F65ADC4A4B001CA591363B64746D4C | mysql_native_password | localhost |
| phpmyadmin | *5FD2B7524254B7F81B32873B1EA6D681503A5CA9 | mysql_native_password | localhost |
+------------------+-------------------------------------------+-----------------------+-----------+
5 rows in set (0.00 sec)

Then run http://yourip_address/YouPHPTube/

Encoder installed okay on different server no problems.

**Comment by DanielnetoDotCom** [comment]
If your problem is on the database user/connection, you probably did not create a MySQL user properly

try to run this ...


`sudo mysql -u root -e "USE mysql;CREATE USER 'youphptube'@'localhost' IDENTIFIED BY 'youphptube';GRANT ALL PRIVILEGES ON *.* TO 'youphptube'@'localhost';UPDATE user SET plugin='mysql_native_password' WHERE User='youphptube'; FLUSH PRIVILEGES; "`

after this, your MySQL username and password will be youphptube

**Comment by k7n2g** [comment]
Hi Daniel have reinstalled the whole lot and added user as above but still wont recognize or connect to mysql database. http://81.150.166.169/YouPHPTube/install/index.php  (so cant add mods)

sudo apt-get install apache2 php libapache2-mod-php php-mysql php-curl php-gd php-intl mysql-server mysql-client ffmpeg git libimage-exiftool-perl php-mbstring php-gettext python
cd /var/www/html
sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube.git
sudo git clone https://github.com/DanielnetoDotCom/YouPHPTube-Encoder.git # only for encoder
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl # only for encoder
sudo chmod a+rx /usr/local/bin/youtube-dl # only for encoder
sudo a2enmod rewrite
sudo phpenmod mbstring
sudo systemctl restart apache2
sudo mysql_secure_installation # set mysql-root-password

sudo mysql -u root -e "USE mysql;CREATE USER 'youphptube'@'localhost' IDENTIFIED BY 'youphptube';GRANT ALL PRIVILEGES ON *.* TO 'youphptube'@'localhost';UPDATE user SET plugin='mysql_native_password' WHERE User='youphptube'; FLUSH PRIVILEGES; "

after this, your MySQL username and password will be youphptube
 STILL GET THIS ERROR:
Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)

**Comment by k7n2g** [comment]
Changed and reinstalled on ubuntu 16.04  still cant get database connection    with user youphptube   followed all instructions still  wont connect

**Comment by DanielnetoDotCom** [comment]
you ill need to google to find out how to create a MySQL user.

but FYI, I can see you are using a blank username and a blank password, definitely you are missing something!

`Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)`

**Comment by k7n2g** [comment]
Hi Daniel  thanks for reply   i have a friend who is much better with ubuntu than me even he cant get it to work it is install as you said and we have used youphptube as user and password  mysql works fine when we access it but cant install Prog wont connect     we have this in   log:
 [Sun Jun 30 10:10:43.279578 2019] [:error] [pid 22050] [client 192.168.1.110:50190] PHP Notice:  Undefined index: systemRootPath in /var/www/html/YouPHPTube/install/checkConfiguration.php on line 11, referer: http://www.cview.mobi/YouPHPTube/install/index.php

we have checked the system root path and it is correct   as /var/www/htm/YouPHPTube   we dont understand what to change and put in  line 11  can you tell us please   Dave

**Comment by akhilleusuggo** [comment]
@k7n2g your problem should have been solved by ```
sudo mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'NEWPASSWORD';
```
since on the logs you're not using any password `Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)`

Try to copy paste again that line . And I don't forget this step as well :

`sudo nano /etc/apache2/apache2.conf`

After editing the above file your code should be like this:

```
<Directory /var/www/>
          Options Indexes FollowSymLinks
          AllowOverride All
          Require all granted
  </Directory>
```

**Comment by k7n2g** [comment]
Hi akhilleusuggo thanks for the reply.
Have done and redone all this checked it is all the same, no typos.  AllowOverride All  in place, can connect freely to mysql as root and youphptube no problem  but 81.150.166.169/YouPHPTube/  install cant connect to mysql  checked port 3306 is open, removed bind-address   so all interfaces can connect, still cant connect,  log file shows this:  

[Sun Jun 30 10:10:43.279578 2019] [:error] [pid 22050] [client 192.168.1.110:50190] PHP Notice: Undefined index: systemRootPath in /var/www/html/YouPHPTube/install/checkConfiguration.php on line 11, referer: http://www.cview.mobi/YouPHPTube/install/index.php   any other ideas you can see from the file above what has been done  i moved from ubuntu 18.04 to 16.04 a fresh install  and still cant connect

**Comment by k7n2g** [comment]
Sorry forgot to say that this error is wrong Connect Error (1045) Access denied for user ''@'localhost' (using password: NO)  i have user with all permissions added   still get no username or password acceptance

**Comment by DanielnetoDotCom** [comment]
Looks, like your configuration.php file, is not correct.

I am not sure what is happening, but the index systemRootPath should be global

If I am you I would try all over again. you miss some step somewhere

**Comment by akhilleusuggo** [comment]
@k7n2g Did you tried to run it on localhost ? What you're linking are 2 different IP , the private IP ([client 192.168.1.110:50190] ) and the public IP ( 81.150.166.169/YouPHPTube/ ) .

I have started using google VPS and I recommend you to open all the ports ( if you have a router firewall ) , one you have everything running fine , close them again , and check only the active ports)

**Comment by k7n2g** [comment]
Hi akhilleusuggo thank you that did it  it was a conflict between  the private IP ([client 192.168.1.110:50190] ) and the public IP ( 81.150.166.169/YouPHPTube/ ) in the Router itself and daniel telling me the path is global  in configuration.php file,  managed to trace it back would never have thought of that many thanks guy and to all who tried to help me  all working now.
